export const GET_PRODUCT ="GET_PRODUCT";
export const DELETE_PRODUCT ="DELETE_USER";
export const ADD_PRODUCT ="ADD_PRODUCT";
export const UPDATE_PRODUCT ="UPDATE_PRODUCT";
export const GET_SINGLE_PRODUCT ="GET_SINGLE_PRODUCT";


